import tribuNewsActions from "../../actions/TribuActions"
import url from "../../url/url";

export function tribuSuites(){

    context('Automatizacion - Tribu', () => {

        it("Section - Tribu", () =>{
        cy.viewport(1200,800)
        url.urltribu()
        tribuNewsActions.clickBotonCerrarTribu1(); 
        tribuNewsActions.clickBotonCerrarTribu2(); 
        tribuNewsActions.ValidarTextoTri();
        tribuNewsActions.validarParrafoTri(); 
        ///Ingresos 
        tribuNewsActions.ValidarTextoIngresos();
        tribuNewsActions.ValidarTextoEnero();
        tribuNewsActions.validarImgEne(); 
        tribuNewsActions.ValidarTextoNoviem(); 
        tribuNewsActions.validarImgNoviem(); 
        tribuNewsActions.ValidarTextoOctub(); 
        tribuNewsActions.validarImgOctub(); 
        tribuNewsActions.ValidarTextoSepti(); 
        tribuNewsActions.validarImgSepti();
        tribuNewsActions.ValidarTextoAgost(); 
        tribuNewsActions.validarImgAgost();
        tribuNewsActions.ValidarTextoJulio(); 
        tribuNewsActions.validarImgJulio();
        tribuNewsActions.ValidarTextoJunio(); 
        tribuNewsActions.validarImgJunio();
        tribuNewsActions.ValidarTextoMayo(); 
        tribuNewsActions.validarImgMayo();
        ///Retiros
        tribuNewsActions.clickBotonRetiros(); 
        tribuNewsActions.ValidarTextoRetiros(); 
        tribuNewsActions.ValidarTextoEneRe(); 
        tribuNewsActions.validarImgEneRe(); 
        tribuNewsActions.ValidarTextoNoviRe(); 
        tribuNewsActions.validarImgNoviRe(); 
        tribuNewsActions.ValidarTextoOctuRe(); 
        tribuNewsActions.validarImgOctuRe();
        tribuNewsActions.ValidarTextoSeptiRe(); 
        tribuNewsActions.validarImgSeptiRe();
        tribuNewsActions.ValidarTextoAgostRe(); 
        tribuNewsActions.validarImgAgostRe();
        tribuNewsActions.ValidarTextoJulioRe(); 
        tribuNewsActions.validarImgJulioRe();
        tribuNewsActions.ValidarTextoJunioRe(); 
        tribuNewsActions.validarImgJunioRe();
        tribuNewsActions.ValidarTextoMayoRe(); 
        tribuNewsActions.validarImgMayoRe();
        tribuNewsActions.ValidarTextoAbrilRe(); 
        tribuNewsActions.validarImgAbrilRe();
        tribuNewsActions.ValidarTextoMarzoRe(); 
        tribuNewsActions.validarImgMarzoRe();
        tribuNewsActions.ValidarTextoFebreroRe(); 
        tribuNewsActions.validarImgFebreroRe();
        tribuNewsActions.ValidarTextoFebreroRe(); 
        tribuNewsActions.validarImgFebreroRe();
        tribuNewsActions.ValidarTextoEneroRe(); 
        tribuNewsActions.validarImgEneroRe();
        ///Convocatorias 
        tribuNewsActions.clickBotonConvoca(); 
        tribuNewsActions.ValidarTextoConvoca(); 
        tribuNewsActions.clickBotonFleCarru(); 
        tribuNewsActions.clickBotonMasInfo(); 
        tribuNewsActions.ValidarTextoInter(); 
        tribuNewsActions.validarImgaInter(); 
        tribuNewsActions.ValidarTextoTips(); 
        tribuNewsActions.validarImgTips();
        ///tribuNewsActions.clickBotonSubir(); 
        ///SST
        tribuNewsActions.clickBotonSST(); 
        tribuNewsActions.ValidarTextoSST();
        tribuNewsActions.ValidarTextoSeguIndu(); 
        tribuNewsActions.ValidarTextoDescu();
        tribuNewsActions.ValidarParrafoDescu();
        tribuNewsActions.clickBotonVermas1();
        tribuNewsActions.ValidarTextoHigiOcupa();
        tribuNewsActions.ValidarTextoPierdas(); 
        tribuNewsActions.ValidarParrafoPierdas();
        tribuNewsActions.clickBotonVermas2(); 
        tribuNewsActions.ValidarTextoHigiOcupa2();
        tribuNewsActions.ValidarTextoComprom(); 
        tribuNewsActions.ValidarParrafoComprom();
        tribuNewsActions.clickBotonVermas3(); 
        tribuNewsActions.ValidarTextoSeguIndu2(); 
        tribuNewsActions.ValidarTextoPostu(); 
        tribuNewsActions.ValidarParrafoPostu(); 
        tribuNewsActions.clickBotonVermas4(); 
        tribuNewsActions.ValidarTextoHigiOcupa3(); 
        tribuNewsActions.ValidarTextoPausas();
        tribuNewsActions.ValidarParrafoPausas();
        tribuNewsActions.clickBotonVermas5();
        ///NOVEDADES
        tribuNewsActions.clickBotonNoved(); 
        tribuNewsActions.ValidarTextoNoved();
        tribuNewsActions.clickPagina1();
        tribuNewsActions.validarTextoPaginas1();
        tribuNewsActions.clickPagina2();
        tribuNewsActions.validarTextoPaginas2();
        tribuNewsActions.clickPagina3();
        tribuNewsActions.validarTextoPaginas3();
        tribuNewsActions.clickPagina4();
        tribuNewsActions.validarTextoPaginas4();
        tribuNewsActions.clickPagina5();
        tribuNewsActions.validarTextoPaginas5();
        tribuNewsActions.clickPagina6();
        tribuNewsActions.validarTextoPaginas6();
        tribuNewsActions.clickPagina7();
        tribuNewsActions.validarTextoPaginas7();
        tribuNewsActions.clickPagina8();
        tribuNewsActions.validarTextoPaginas8();
        tribuNewsActions.clickPagina9();
        tribuNewsActions.validarTextoPaginas9();
        });
    });
        
}